import { useEffect, useMemo, useState } from 'react'
import { Check, Copy, ExternalLink, FolderGit2, Menu, Search, ShieldAlert, Star, Terminal, X } from 'lucide-react'
import './App.css'

const repos = [
  { name: 'CYBERDEK ATLAS', path: '~/cyberdek-atlas', type: 'Painel local', risk: 'Baixo', status: 'Pronto para usar', note: 'Diretório local com busca e favoritos.', command: 'cd ~/cyberdek-atlas && npm run serve' },
  { name: 'Anubis', path: '~/Anubis', type: 'Enumeração de subdomínios', risk: 'Médio', status: 'Requer dependências Python', note: 'Comece pela documentação e pelos requisitos.', command: 'cd ~/Anubis && anubis --help' },
  { name: 'dirsearch', path: '~/dirsearch', type: 'Teste de caminhos web', risk: 'Médio', status: 'Use somente em laboratório', note: 'Leia o guia antes de qualquer uso autorizado.', command: 'cd ~/dirsearch && python3 dirsearch.py --help' },
  { name: 'XSStrike', path: '~/XSStrike', type: 'Detecção XSS', risk: 'Alto', status: 'Documentação primeiro', note: 'Ferramenta de alto impacto: o painel só oferece ajuda local.', command: 'cd ~/XSStrike && python xsstrike.py --help' },
  { name: 'Commix', path: '~/commix', type: 'Teste de injeção', risk: 'Alto', status: 'Use apenas em laboratório', note: 'Prioridade alta de risco. Não execute contra sistemas reais.', command: 'cd ~/commix && python commix.py -h' },
  { name: 'AllHackingTools', path: '~/AllHackingTools', type: 'Agregador de ferramentas', risk: 'Alto', status: 'Revisar antes de executar', note: 'Não use menus automáticos; leia os arquivos primeiro.', command: 'cd ~/AllHackingTools && sed -n \'1,160p\' README.md' },
  { name: 'DarkFly-Tool', path: '~/DarkFly-Tool', type: 'Agregador legado', risk: 'Alto', status: 'Legado: não recomendado', note: 'Não instale dependências legadas só para executar.', command: 'cd ~/DarkFly-Tool && sed -n \'1,140p\' README.md' },
  { name: 'Termux-Kali', path: '~/Termux-Kali', type: 'Ambiente Linux', risk: 'Médio', status: 'Revisar compatibilidade', note: 'Leia scripts e verifique espaço antes de instalar.', command: 'cd ~/Termux-Kali && sed -n \'1,160p\' README.md' },
]

function App() {
  const [catalog, setCatalog] = useState([])
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('ALL')
  const [favoritesOnly, setFavoritesOnly] = useState(false)
  const [favorites, setFavorites] = useState(() => new Set(JSON.parse(localStorage.getItem('cyberdek-favorites') || '[]')))
  const [visible, setVisible] = useState(24)
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedRepo, setSelectedRepo] = useState(null)
  const [copied, setCopied] = useState('')

  useEffect(() => { fetch(`${import.meta.env.BASE_URL}atlas-catalog.json`).then(response => response.json()).then(setCatalog).catch(() => setCatalog([])) }, [])
  const categories = useMemo(() => Object.entries(catalog.reduce((out, item) => ({ ...out, [item.category]: (out[item.category] || 0) + 1 }), {})).sort(([a], [b]) => a.localeCompare(b)), [catalog])
  const results = useMemo(() => catalog.filter(item => (category === 'ALL' || item.category === category) && (!favoritesOnly || favorites.has(item.id)) && `${item.title} ${item.category} ${item.url}`.toLowerCase().includes(query.toLowerCase())), [catalog, category, favorites, favoritesOnly, query])
  const chooseCategory = (value) => { setCategory(value); setVisible(24) }
  const toggleFavorite = (id) => setFavorites(old => { const next = new Set(old); next.has(id) ? next.delete(id) : next.add(id); localStorage.setItem('cyberdek-favorites', JSON.stringify([...next])); return next })
  const copy = async (value) => { await navigator.clipboard?.writeText(value); setCopied(value); setTimeout(() => setCopied(''), 1600) }

  return <main>
    <div className="notice">CARTEL 576 · ATLAS LOCAL · {catalog.length || '…'} REFERÊNCIAS PRESERVADAS</div>
    <header className="site-header"><a className="wordmark" href="#top">CARTEL<span>576</span></a><nav className={menuOpen ? 'open' : ''}><a href="#directory">Acervo</a><a href="#repos">Repositórios</a><a href="#safety">Uso seguro</a></nav><button className="menu" onClick={() => setMenuOpen(open => !open)} aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="top" className="hero"><div><p className="kicker"><i /> SISTEMA LOCAL · TERMUX</p><h1>Seu atlas de<br /><em>referências.</em></h1><p className="intro">Links, ferramentas e repositórios em um lugar seu. Pesquise primeiro, entenda o contexto e use apenas em ambientes autorizados.</p><a className="cta" href="#directory">Abrir o acervo <span>→</span></a></div><aside className="terminal-card"><div className="terminal-head"><i /> atlas/status.local</div><dl><div><dt>REFERÊNCIAS</dt><dd>1.454</dd></div><div><dt>NAVEGÁVEIS</dt><dd>{catalog.length || '…'}</dd></div><div><dt>REVISÃO</dt><dd>130</dd></div><div><dt>SALVOS</dt><dd>{favorites.size}</dd></div></dl><p><b>$</b> arquivo local disponível</p></aside></section>
    <section id="directory" className="directory"><div className="section-title"><p className="kicker">O ACERVO</p><h2>Encontre o que você já tem.</h2><p>O catálogo original do Cyberdek Atlas, preservado localmente e pesquisável.</p></div><div className="searchbox"><Search /><input value={query} onChange={event => { setQuery(event.target.value); setVisible(24) }} placeholder="Pesquisar nome, domínio ou categoria…" /><span>{results.length.toLocaleString('pt-BR')}</span></div><div className="directory-actions"><button className={favoritesOnly ? 'active' : ''} onClick={() => { setFavoritesOnly(value => !value); setVisible(24) }}><Star size={14} fill={favoritesOnly ? 'currentColor' : 'none'} /> Salvos · {favorites.size}</button><span>Escolha uma categoria abaixo</span></div><div className="chips"><button className={category === 'ALL' ? 'active' : ''} onClick={() => chooseCategory('ALL')}>TODAS · {catalog.length}</button>{categories.map(([name, count]) => <button className={category === name ? 'active' : ''} onClick={() => chooseCategory(name)} key={name}>{name} · {count}</button>)}</div><div className="link-list">{results.slice(0, visible).map(item => <article className="reference" key={item.id}><p>{item.category}</p><button onClick={() => toggleFavorite(item.id)} aria-label={`Salvar ${item.title}`} className={favorites.has(item.id) ? 'saved' : ''}>{favorites.has(item.id) ? '★' : '☆'}</button><h3>{item.title}</h3><span>{new URL(item.url).hostname.replace(/^www\./, '')}</span><a href={item.url} target="_blank" rel="noreferrer">Abrir referência <ExternalLink size={13} /></a></article>)}</div>{!results.length && <p className="empty">Nenhuma referência encontrada.</p>}{results.length > visible && <button className="more" onClick={() => setVisible(value => value + 48)}>Carregar mais referências</button>}</section>
    <section id="safety" className="safety"><ShieldAlert /><div><p className="kicker">PERIGO DE USO · 130 ITENS</p><h2>Uma fila de revisão, não um atalho.</h2><p>Os itens sensíveis do arquivo foram preservados localmente e continuam fora do diretório navegável. Nenhuma ação de ataque, scan ou execução é exposta aqui.</p></div></section>
    <section id="repos" className="repos"><div className="section-title"><p className="kicker">MAPA DO TERMUX</p><h2>Repositórios que você já usa.</h2><p>Toque em um repositório para ver notas e comandos seguros de orientação.</p></div><div className="repo-list">{repos.map(repo => <button className="repo-row" key={repo.name} onClick={() => setSelectedRepo(repo)}><FolderGit2 /><div><p>{repo.risk === 'Alto' ? 'RISCO ALTO' : `RISCO ${repo.risk.toUpperCase()}`} · {repo.type}</p><h3>{repo.name}</h3><span>{repo.path} · {repo.status}</span></div><span className="open-arrow">→</span></button>)}</div></section>
    <section className="termux-guide"><div className="section-title"><p className="kicker">COMECE PELO TERMUX</p><h2>Comandos para se orientar.</h2><p>Estes comandos só navegam, listam ou leem arquivos. Copie um por vez e entenda a saída antes do próximo.</p></div><div className="command-grid"><Command label="Onde estou?" description="Mostra a pasta atual." value="pwd" copy={copy} copied={copied} /><Command label="O que existe aqui?" description="Lista arquivos, inclusive os ocultos." value="ls -la" copy={copy} copied={copied} /><Command label="Entrar em um projeto" description="Troque pelo caminho do repositório." value="cd ~/cartel-576" copy={copy} copied={copied} /><Command label="Ler um README" description="Exibe somente as primeiras linhas." value="sed -n '1,160p' README.md" copy={copy} copied={copied} /></div></section>
    <footer>LOCAL-FIRST · FAVORITOS SALVOS NESTE NAVEGADOR · CARTEL 576</footer>
    {selectedRepo && <RepoPanel repo={selectedRepo} copied={copied} copy={copy} close={() => setSelectedRepo(null)} />}
  </main>
}
function Command({ label, description, value, copy, copied }) { return <article className="command-card"><p>{label}</p><span>{description}</span><code>$ {value}</code><button onClick={() => copy(value)}>{copied === value ? <><Check size={14} /> copiado</> : <><Copy size={14} /> copiar</>}</button></article> }
function RepoPanel({ repo, copied, copy, close }) { return <div className="drawer-backdrop" onMouseDown={close}><aside className="drawer" onMouseDown={event => event.stopPropagation()} role="dialog" aria-modal="true" aria-label={`Detalhes de ${repo.name}`}><button className="drawer-close" onClick={close} aria-label="Fechar"><X /></button><p className="kicker">{repo.risk === 'Alto' ? 'RISCO ALTO' : `RISCO ${repo.risk.toUpperCase()}`} · LOCAL</p><h2>{repo.name}</h2><p className="drawer-path"><Terminal size={14} /> {repo.path}</p><div className="drawer-section"><b>Status</b><p>{repo.status}</p></div><div className="drawer-section"><b>Nota de orientação</b><p>{repo.note}</p></div><div className="drawer-command"><span>AJUDA LOCAL</span><code>$ {repo.command}</code><button onClick={() => copy(repo.command)}>{copied === repo.command ? <><Check size={14} /> Copiado</> : <><Copy size={14} /> Copiar comando</>}</button></div><p className="drawer-foot">Este painel não executa comandos. Use somente ambientes próprios ou autorizados.</p></aside></div> }
export default App
